### ISSUE TITLE
AttributeError: 'Options' object has no attribute 'headless'

### ISSUE THREAD

**Issue by ghost** [protomens/totui#3]
```
Traceback (most recent call last):
  File "/home/secret/venv/totui/bin/totui", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/secret/venv/totui/lib/python3.11/site-packages/totui/totui.py", line 1201, in main
    TS = SeleniumTradeOgre()    
         ^^^^^^^^^^^^^^^^^^^
  File "/home/secret/venv/totui/lib/python3.11/site-packages/totui_selenium/totui_selenium.py", line 51, in __init__
    self.driver = self.createDriverInstance()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/secret/venv/totui/lib/python3.11/site-packages/totui_selenium/totui_selenium.py", line 56, in createDriverInstance
    mydriver = uc.Chrome(options=options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/secret/venv/totui/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 398, in __init__
    if headless or options.headless:
                   ^^^^^^^^^^^^^^^^
AttributeError: 'Options' object has no attribute 'headless'
```

**Comment by protomens** [comment]
Downgraded selenium dependency to 4.12.0 on pip install.

Please create a new python venv and install fresh. 

New version is: totui v1.9.1

https://github.com/protomens/totui/commit/a13cfea80f4ab870c1a2af56ba112def563fdecd

**Comment by protomens** [comment]
https://stackoverflow.com/questions/77191221/undetected-chromedriver-attributeerror-chromeoptions-object-has-no-attribute
